# Generated by Django 5.2.6 on 2025-09-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField(choices=[('upload', 'Upload'), ('delete', 'Delete'), ('update', 'Update')], db_index=True, verbose_name='Action Type')),
                ('result', models.TextField(choices=[('success', 'Success'), ('no_effect', 'No Effect'), ('rejected', 'Rejected'), ('error', 'Error')], db_index=True, verbose_name='Action Result')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(blank=True, default=dict, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Strip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.TextField(db_index=True)),
                ('date', models.DateField(db_index=True)),
                ('dep', models.TextField(db_index=True)),
                ('des', models.TextField(db_index=True)),
                ('sector', models.TextField(db_index=True)),
                ('point1time', models.DateTimeField(db_index=True)),
                ('sector_end', models.DateTimeField(db_index=True)),
                ('journey_id', models.TextField(db_index=True)),
                ('ssrcode', models.TextField(blank=True, null=True)),
                ('register', models.TextField(blank=True, null=True)),
                ('aircraftname', models.TextField(blank=True, null=True)),
                ('aircrafttype', models.TextField(blank=True, null=True)),
                ('route', models.TextField(blank=True, null=True)),
                ('point1', models.TextField()),
                ('point2', models.TextField(blank=True, null=True)),
                ('point2time', models.DateTimeField(blank=True, null=True)),
                ('point3', models.TextField(blank=True, null=True)),
                ('point3time', models.DateTimeField(blank=True, null=True)),
                ('point4', models.TextField(blank=True, null=True)),
                ('point4time', models.DateTimeField(blank=True, null=True)),
                ('point5', models.TextField(blank=True, null=True)),
                ('point5time', models.DateTimeField(blank=True, null=True)),
                ('point6', models.TextField(blank=True, null=True)),
                ('point6time', models.DateTimeField(blank=True, null=True)),
                ('speed', models.TextField(blank=True, null=True)),
                ('cfl', models.TextField(blank=True, null=True)),
                ('rfl', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': [('import_strip', 'Can import strip'), ('import_outdated_strip', 'Can import outdated strip')],
                'constraints': [models.UniqueConstraint(fields=('callsign', 'date', 'dep', 'des', 'sector'), name='unique_strip_sector_date'), models.UniqueConstraint(fields=('journey_id', 'sector'), name='unique_strip_journey_sector')],
            },
        ),
    ]
